use anyhow::{Context, bail};
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

use crate::backend::mods;
use crate::backend::paths;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModBlacklistEntry {
    pub name: String,
    pub file: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ModBlacklistProfile {
    pub name: String,
    pub mods: Vec<ModBlacklistEntry>,
    #[serde(default)]
    pub mod_options_order: Vec<String>,
}

fn profiles_dir_path(game_path: &str) -> PathBuf {
    Path::new(game_path).join("celemod_blacklist_profiles")
}

fn blacklist_path(game_path: &str) -> PathBuf {
    mods::mods_dir_path(game_path).join("blacklist.txt")
}

fn mod_options_order_path(game_path: &str) -> PathBuf {
    mods::mods_dir_path(game_path).join("modoptionsorder.txt")
}

fn validate_profile_name(profile_name: &str) -> anyhow::Result<String> {
    let trimmed = profile_name.trim();
    if trimmed.is_empty() {
        bail!("Profile name cannot be empty");
    }
    if trimmed.contains('/') || trimmed.contains('\\') || trimmed.chars().any(char::is_control) {
        bail!("Profile name contains unsupported path characters");
    }
    Ok(trimmed.to_string())
}

fn profile_path(game_path: &str, profile_name: &str) -> anyhow::Result<PathBuf> {
    let profile_name = validate_profile_name(profile_name)?;
    Ok(profiles_dir_path(game_path).join(format!("{profile_name}.json")))
}

fn ensure_workspace(game_path: &str) -> anyhow::Result<()> {
    if !paths::verify_celeste_install(game_path) {
        bail!("{} is not a valid Celeste install", game_path);
    }
    fs::create_dir_all(mods::mods_dir_path(game_path))?;
    fs::create_dir_all(profiles_dir_path(game_path))?;
    Ok(())
}

fn read_blacklist_lines(game_path: &str) -> anyhow::Result<Vec<String>> {
    let blacklist = blacklist_path(game_path);
    if !blacklist.exists() {
        return Ok(Vec::new());
    }

    let content = fs::read_to_string(&blacklist)
        .with_context(|| format!("Failed to read blacklist file {}", blacklist.display()))?;
    Ok(content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(ToString::to_string)
        .collect())
}

fn read_mod_options_order(game_path: &str) -> anyhow::Result<Vec<String>> {
    let path = mod_options_order_path(game_path);
    if !path.exists() {
        return Ok(Vec::new());
    }

    let content = fs::read_to_string(&path)
        .with_context(|| format!("Failed to read mod options order {}", path.display()))?;
    Ok(content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(ToString::to_string)
        .collect())
}

fn write_mod_options_order(game_path: &str, order: &[String]) -> anyhow::Result<()> {
    let path = mod_options_order_path(game_path);
    if order.is_empty() {
        if path.exists() {
            fs::remove_file(&path)
                .with_context(|| format!("Failed to remove {}", path.display()))?;
        }
        return Ok(());
    }

    let content = format!(
        "# Mod Options order\n# This file is generated by CeleMod\n\n{}\n",
        order.join("\n")
    );
    fs::write(&path, content).with_context(|| format!("Failed to write {}", path.display()))?;
    Ok(())
}

fn sort_profiles(profiles: &mut [ModBlacklistProfile]) {
    profiles.sort_by(|left, right| {
        let left_key = (left.name != "Default", left.name.to_lowercase());
        let right_key = (right.name != "Default", right.name.to_lowercase());
        left_key.cmp(&right_key)
    });
}

fn sort_profile_mods(mods: &mut [ModBlacklistEntry]) {
    mods.sort_by(|left, right| left.name.to_lowercase().cmp(&right.name.to_lowercase()));
}

fn save_profile(game_path: &str, profile: &ModBlacklistProfile) -> anyhow::Result<()> {
    let mut normalized = profile.clone();
    normalized.name = validate_profile_name(&normalized.name)?;
    sort_profile_mods(&mut normalized.mods);
    let path = profile_path(game_path, &normalized.name)?;
    let content = serde_json::to_string_pretty(&normalized)?;
    fs::write(&path, content).with_context(|| format!("Failed to write {}", path.display()))?;
    Ok(())
}

fn load_default_profile_from_files(game_path: &str) -> anyhow::Result<Option<ModBlacklistProfile>> {
    let blacklist_lines = read_blacklist_lines(game_path)?;
    if blacklist_lines.is_empty() {
        return Ok(None);
    }

    let installed_mods = mods::get_installed_mods(game_path)?;
    let entries = blacklist_lines
        .into_iter()
        .map(|file| {
            let name = installed_mods
                .iter()
                .find(|installed_mod| installed_mod.file == file)
                .map(|installed_mod| installed_mod.name.clone())
                .unwrap_or_else(|| file.clone());
            ModBlacklistEntry { name, file }
        })
        .collect();

    Ok(Some(ModBlacklistProfile {
        name: "Default".to_string(),
        mods: entries,
        mod_options_order: read_mod_options_order(game_path)?,
    }))
}

pub fn get_mod_blacklist_profiles(game_path: &str) -> anyhow::Result<Vec<ModBlacklistProfile>> {
    ensure_workspace(game_path)?;

    let profiles_dir = profiles_dir_path(game_path);
    let mut profiles = Vec::new();

    let mut entries = fs::read_dir(&profiles_dir)
        .with_context(|| format!("Failed to read {}", profiles_dir.display()))?
        .collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();
        if path.extension().and_then(|value| value.to_str()) != Some("json") {
            continue;
        }

        let content = match fs::read_to_string(&path) {
            Ok(content) => content,
            Err(error) => {
                eprintln!(
                    "Failed to read blacklist profile {}: {error}",
                    path.display()
                );
                continue;
            }
        };

        match serde_json::from_str::<ModBlacklistProfile>(&content) {
            Ok(mut profile) => {
                if let Ok(validated_name) = validate_profile_name(&profile.name) {
                    profile.name = validated_name;
                    sort_profile_mods(&mut profile.mods);
                    profiles.push(profile);
                } else {
                    eprintln!(
                        "Skipping blacklist profile with invalid name in {}",
                        path.display()
                    );
                }
            }
            Err(error) => {
                eprintln!(
                    "Failed to parse blacklist profile {}: {error}",
                    path.display()
                );
            }
        }
    }

    if profiles.is_empty() {
        if let Some(profile) = load_default_profile_from_files(game_path)? {
            save_profile(game_path, &profile)?;
            profiles.push(profile);
        }
    }

    if profiles.is_empty() {
        let profile = ModBlacklistProfile {
            name: "Default".to_string(),
            mods: Vec::new(),
            mod_options_order: Vec::new(),
        };
        save_profile(game_path, &profile)?;
        profiles.push(profile);
    }

    sort_profiles(&mut profiles);
    Ok(profiles)
}

pub fn get_current_profile(game_path: &str) -> anyhow::Result<String> {
    let profiles = get_mod_blacklist_profiles(game_path)?;
    let blacklist = blacklist_path(game_path);
    if !blacklist.exists() {
        return Ok("Default".to_string());
    }

    let content = fs::read_to_string(&blacklist)
        .with_context(|| format!("Failed to read blacklist file {}", blacklist.display()))?;
    let profile_name = content
        .lines()
        .next()
        .and_then(|line| line.strip_prefix("# Profile: "))
        .unwrap_or("Default")
        .trim();

    if profiles.iter().any(|profile| profile.name == profile_name) {
        Ok(profile_name.to_string())
    } else {
        Ok("Default".to_string())
    }
}

pub fn apply_mod_blacklist_profile(
    game_path: &str,
    profile_name: &str,
    always_on_mods: &[String],
) -> anyhow::Result<()> {
    let profile_name = validate_profile_name(profile_name)?;
    let mut profile = get_mod_blacklist_profiles(game_path)?
        .into_iter()
        .find(|profile| profile.name == profile_name)
        .context("Profile not found")?;
    let installed_mods = mods::get_installed_mods(game_path)?;
    let always_on_mods: HashSet<&str> = always_on_mods.iter().map(String::as_str).collect();

    for entry in &mut profile.mods {
        if let Some(installed_mod) = installed_mods
            .iter()
            .find(|installed| installed.name == entry.name)
        {
            entry.file = installed_mod.file.clone();
        }
    }
    sort_profile_mods(&mut profile.mods);
    save_profile(game_path, &profile)?;

    let blacklisted_names: HashSet<&str> = profile
        .mods
        .iter()
        .map(|entry| entry.name.as_str())
        .collect();
    let blacklisted_files = installed_mods
        .iter()
        .filter(|installed_mod| {
            blacklisted_names.contains(installed_mod.name.as_str())
                && !always_on_mods.contains(installed_mod.name.as_str())
        })
        .map(|installed_mod| installed_mod.file.clone())
        .collect::<Vec<_>>();

    let mut content = format!(
        "# Profile: {}\n# This file is generated by CeleMod\n\n",
        profile.name
    );
    if !blacklisted_files.is_empty() {
        content.push_str(&blacklisted_files.join("\n"));
        content.push('\n');
    }

    let blacklist = blacklist_path(game_path);
    fs::write(&blacklist, content)
        .with_context(|| format!("Failed to write blacklist file {}", blacklist.display()))?;
    write_mod_options_order(game_path, &profile.mod_options_order)?;

    Ok(())
}

pub fn set_mod_options_order(
    game_path: &str,
    profile_name: &str,
    order: Vec<String>,
) -> anyhow::Result<()> {
    let profile_name = validate_profile_name(profile_name)?;
    let mut profile = get_mod_blacklist_profiles(game_path)?
        .into_iter()
        .find(|profile| profile.name == profile_name)
        .context("Profile not found")?;

    profile.mod_options_order = order;
    save_profile(game_path, &profile)?;
    write_mod_options_order(game_path, &profile.mod_options_order)
}

pub fn get_current_blacklist_content(game_path: &str) -> anyhow::Result<String> {
    ensure_workspace(game_path)?;
    let blacklist = blacklist_path(game_path);
    if !blacklist.exists() {
        return Ok(String::new());
    }

    fs::read_to_string(&blacklist)
        .with_context(|| format!("Failed to read blacklist file {}", blacklist.display()))
}

pub fn sync_blacklist_profile_from_file(
    game_path: &str,
    profile_name: &str,
    always_on_mods: &[String],
) -> anyhow::Result<()> {
    let profile_name = validate_profile_name(profile_name)?;
    let blacklist = blacklist_path(game_path);
    if !blacklist.exists() {
        return Ok(());
    }

    let content = fs::read_to_string(&blacklist)
        .with_context(|| format!("Failed to read blacklist file {}", blacklist.display()))?;
    let installed_mods = mods::get_installed_mods(game_path)?;
    let existing_profile = get_mod_blacklist_profiles(game_path)?
        .into_iter()
        .find(|profile| profile.name == profile_name);
    let existing_order = existing_profile
        .as_ref()
        .map(|profile| profile.mod_options_order.clone())
        .unwrap_or_default();
    let always_on_set = always_on_mods
        .iter()
        .map(String::as_str)
        .collect::<HashSet<_>>();

    let mut entries = content
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|file| {
            let name = installed_mods
                .iter()
                .find(|installed_mod| installed_mod.file == file)
                .map(|installed_mod| installed_mod.name.clone())
                .unwrap_or_else(|| file.to_string());
            ModBlacklistEntry {
                name,
                file: file.to_string(),
            }
        })
        .collect::<Vec<_>>();

    if let Some(profile) = existing_profile {
        for entry in profile
            .mods
            .into_iter()
            .filter(|entry| always_on_set.contains(entry.name.as_str()))
        {
            if entries.iter().all(|existing| existing.name != entry.name) {
                entries.push(entry);
            }
        }
    }

    sort_profile_mods(&mut entries);
    save_profile(
        game_path,
        &ModBlacklistProfile {
            name: profile_name,
            mods: entries,
            mod_options_order: existing_order,
        },
    )
}

pub fn switch_mod_blacklist_profile(
    game_path: &str,
    profile_name: &str,
    mods_to_switch: Vec<ModBlacklistEntry>,
    enabled: bool,
) -> anyhow::Result<()> {
    let profile_name = validate_profile_name(profile_name)?;
    let mut profile = get_mod_blacklist_profiles(game_path)?
        .into_iter()
        .find(|profile| profile.name == profile_name)
        .context("Profile not found")?;

    let mod_names = mods_to_switch
        .iter()
        .map(|entry| entry.name.as_str())
        .collect::<HashSet<_>>();

    if enabled {
        profile
            .mods
            .retain(|entry| !mod_names.contains(entry.name.as_str()));
    } else {
        for mod_entry in mods_to_switch {
            if let Some(existing_entry) = profile
                .mods
                .iter_mut()
                .find(|entry| entry.name == mod_entry.name)
            {
                existing_entry.file = mod_entry.file;
            } else {
                profile.mods.push(mod_entry);
            }
        }
    }

    sort_profile_mods(&mut profile.mods);
    save_profile(game_path, &profile)
}

pub fn new_mod_blacklist_profile(game_path: &str, profile_name: &str) -> anyhow::Result<()> {
    ensure_workspace(game_path)?;
    let profile_name = validate_profile_name(profile_name)?;
    let path = profile_path(game_path, &profile_name)?;
    if path.exists() {
        bail!("Profile already exists");
    }

    save_profile(
        game_path,
        &ModBlacklistProfile {
            name: profile_name,
            mods: Vec::new(),
            mod_options_order: Vec::new(),
        },
    )
}

pub fn remove_mod_blacklist_profile(game_path: &str, profile_name: &str) -> anyhow::Result<()> {
    ensure_workspace(game_path)?;
    let path = profile_path(game_path, profile_name)?;
    if !path.exists() {
        bail!("Profile not found");
    }
    fs::remove_file(&path).with_context(|| format!("Failed to remove {}", path.display()))?;
    Ok(())
}

pub fn remove_mods_from_profiles(
    game_path: &str,
    removed_names: &HashSet<String>,
    removed_files: &HashSet<String>,
    always_on_mods: &[String],
) -> anyhow::Result<Vec<String>> {
    ensure_workspace(game_path)?;
    let profiles = get_mod_blacklist_profiles(game_path)?;
    let mut updated_profiles = Vec::new();

    for mut profile in profiles {
        let original_mod_count = profile.mods.len();
        let original_order_count = profile.mod_options_order.len();

        profile.mods.retain(|entry| {
            !removed_names.contains(&entry.name) && !removed_files.contains(&entry.file)
        });
        profile
            .mod_options_order
            .retain(|file| !removed_files.contains(file));

        if profile.mods.len() != original_mod_count
            || profile.mod_options_order.len() != original_order_count
        {
            save_profile(game_path, &profile)?;
            updated_profiles.push(profile.name);
        }
    }

    if let Ok(current_profile) = get_current_profile(game_path) {
        let _ = apply_mod_blacklist_profile(game_path, &current_profile, always_on_mods);
    }

    Ok(updated_profiles)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::time::{SystemTime, UNIX_EPOCH};

    static TEST_COUNTER: AtomicUsize = AtomicUsize::new(0);

    struct TestGameDir {
        path: PathBuf,
    }

    impl TestGameDir {
        fn new() -> Self {
            let timestamp = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("clock drift")
                .as_nanos();
            let sequence = TEST_COUNTER.fetch_add(1, Ordering::Relaxed);
            let path =
                std::env::temp_dir().join(format!("celemod-wayland-test-{timestamp}-{sequence}"));
            fs::create_dir_all(path.join("Mods")).expect("failed to create Mods directory");
            fs::write(path.join("Celeste"), b"").expect("failed to create Celeste marker");
            Self { path }
        }

        fn path(&self) -> &str {
            self.path.to_str().expect("temp path should be valid UTF-8")
        }
    }

    impl Drop for TestGameDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.path);
        }
    }

    fn write_sample_mod(game: &TestGameDir, dir_name: &str, mod_name: &str, version: &str) {
        let mod_dir = Path::new(game.path()).join("Mods").join(dir_name);
        fs::create_dir_all(&mod_dir).expect("failed to create sample mod");
        fs::write(
            mod_dir.join("everest.yaml"),
            format!(
                "- Name: {mod_name}\n  Version: {version}\n  Dependencies:\n    - Name: Helper\n      Version: 1.2.3\n"
            ),
        )
        .expect("failed to write sample everest.yaml");
    }

    #[test]
    fn applies_profile_to_blacklist_file() {
        let game = TestGameDir::new();
        write_sample_mod(&game, "TestMod", "Sample.Mod", "1.0.0");

        let installed_mods = mods::get_installed_mods(game.path()).expect("mod scan should work");
        assert_eq!(installed_mods.len(), 1);
        assert_eq!(installed_mods[0].name, "Sample.Mod");

        new_mod_blacklist_profile(game.path(), "Disabled").expect("profile creation should work");
        switch_mod_blacklist_profile(
            game.path(),
            "Disabled",
            vec![ModBlacklistEntry {
                name: installed_mods[0].name.clone(),
                file: installed_mods[0].file.clone(),
            }],
            false,
        )
        .expect("switch should update profile");
        set_mod_options_order(
            game.path(),
            "Disabled",
            vec![installed_mods[0].file.clone()],
        )
        .expect("order update should succeed");
        apply_mod_blacklist_profile(game.path(), "Disabled", &[])
            .expect("profile apply should succeed");

        let blacklist = fs::read_to_string(blacklist_path(game.path()))
            .expect("blacklist file should exist after apply");
        assert!(blacklist.contains("# Profile: Disabled"));
        assert!(blacklist.contains("TestMod"));

        let mod_options = fs::read_to_string(mod_options_order_path(game.path()))
            .expect("modoptionsorder should exist after apply");
        assert!(mod_options.contains("TestMod"));
        assert_eq!(
            get_current_profile(game.path()).expect("current profile should resolve"),
            "Disabled"
        );
    }

    #[test]
    fn syncs_profile_from_blacklist_file() {
        let game = TestGameDir::new();
        write_sample_mod(&game, "AlphaPack", "Alpha.Mod", "1.0.0");
        write_sample_mod(&game, "BetaPack", "Beta.Mod", "1.1.0");

        new_mod_blacklist_profile(game.path(), "Imported").expect("profile creation should work");
        set_mod_options_order(game.path(), "Imported", vec!["BetaPack".to_string()])
            .expect("order update should succeed");

        fs::write(
            blacklist_path(game.path()),
            "# Profile: Imported\n# This file is generated by CeleMod\n\nAlphaPack\n",
        )
        .expect("failed to seed blacklist file");

        sync_blacklist_profile_from_file(game.path(), "Imported", &[])
            .expect("sync should succeed");

        let profile = get_mod_blacklist_profiles(game.path())
            .expect("profiles should load")
            .into_iter()
            .find(|profile| profile.name == "Imported")
            .expect("Imported profile should exist");
        assert_eq!(profile.mods.len(), 1);
        assert_eq!(profile.mods[0].name, "Alpha.Mod");
        assert_eq!(profile.mods[0].file, "AlphaPack");
        assert_eq!(profile.mod_options_order, vec!["BetaPack".to_string()]);
    }
}
